### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by webcorptech** [Spence-S/simple-pug-loader#11]
ERROR in   Error: Child compilation failed:
  Module build failed (from ./node_modules/simple-pug-loader/index.js):
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
      at new NodeError (internal/errors.js:322:7)
      at validateString (internal/validators.js:124:11)
      at Object.normalize (path.js:1104:5)
      at Object.module.exports ({project-path}/node_modules/simple-pug-loader/index.js:104:38)
  ModuleBuildError: Module build failed (from ./node_modules/simple-pug-loader/index.js):

**Comment by webcorptech** [comment]
> ERROR in Error: Child compilation failed: Module build failed (from ./node_modules/simple-pug-loader/index.js): TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at new NodeError (internal/errors.js:322:7) at validateString (internal/validators.js:124:11) at Object.normalize (path.js:1104:5) at Object.module.exports ({project-path}/node_modules/simple-pug-loader/index.js:104:38) ModuleBuildError: Module build failed (from ./node_modules/simple-pug-loader/index.js):

Path inside index.pug is worng
